### PR TITLE
minimal setup and Nix config

### PR DESCRIPTION
**Pull request by Kha**
Minimal set of dependencies to execute `temci short exec`.

/cc @sgraf812

### CODE REVIEW

**Comment by Kha** [comment]
Note: cpuset does not actually work because of https://github.com/parttimenerd/temci/blob/0ef47893c64ba8b3a63960c76688efb5ea287b69/temci/run/cpuset.py#L311, which in Nix calls a Python executable that (probably) doesn't know about `cpuset`. Running temci as non-root works fine though.

**Comment by sgraf812** [comment]
Builds fine for me :+1: Just can't seem to remember how to benchmark e.g. `true` with it...

**Comment by sgraf812** [comment]
Ah, `-wd`

**Comment by sgraf812** [comment]
LGTM

**Pull request merged**
