### PR TITLE
Remove fn dependency and use Python 3.10 in CI

### LINKED ISSUE #140: Fn dependency does not work on Python 3.10
Also see https://github.com/kachayev/fn.py/issues/91

### PR DESCRIPTION
**Pull request by eiennohito**
Fixes #140 

Tests seem to pass (on Python 3.10)

### CODE REVIEW

**Comment by parttimenerd** [comment]
We have to see what the CI does. I (or someone else) should also remove `fn` from the `requirements.txt` and `flake.nix`, as well as adding Python 3.10 as a CI target.

**Comment by eiennohito** [comment]
Ah, once more 3.1, it is parsed as number, yes?

**Comment by parttimenerd** [comment]
I'm going to release a new version on pypi soon

**Comment by eiennohito** [comment]
Thanks for the quick clarification!
And I hate yaml :p

**Comment by parttimenerd** [comment]
YAML has its pros and cons. But yes, certain aspects make life far harder than it should be.

Feel free to open issues and PRs if you find any error or missing functionality.

**Pull request merged**
